# Generated by Django 5.2.17 on 2026-09-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_company_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="company_code_not_empty",
            ),
        ),
    ]
