# Generated by Django 5.2.17 on 2026-09-18 12:37

from django.db import migrations

def create_system_user(apps, schema_editor):
    Company = apps.get_model("accounts", "Company")
    User = apps.get_model("accounts", "User")
    company, _ = Company.objects.get_or_create(
        code="SYSTEM",
        defaults={"name": "System", "is_active": False},
    )
    user, created = User.objects.get_or_create(email="system@internal", defaults={
        "company": company,
        "full_name": "System",
        "password": "!",
        "is_staff": False,
        "is_superuser": False,
        "is_active": False,
    })

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_company"),
    ]

    operations = [
        migrations.RunPython(create_system_user, migrations.RunPython.noop)
    ]


