# Generated by Django 5.2.17 on 2026-09-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_company_options"),
        ("catalog", "0012_alter_product_sku_alter_product_uom"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stockquant",
            constraint=models.UniqueConstraint(
                fields=("company", "product", "location"),
                name="uniq_stock_quant_per_company_product_location",
            ),
        ),
    ]
