# Generated by Django 5.2.17 on 2026-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_company_options"),
        ("catalog", "0012_alter_product_sku_alter_product_uom"),
        ("inventory", "0003_stockmove"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stockquant",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", models.F("reserved_qty"))),
                name="reserved_qty_lte_quantity",
            ),
        ),
    ]
