# Generated by Django 5.2.17 on 2026-09-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_company_options"),
        ("catalog", "0012_alter_product_sku_alter_product_uom"),
        ("inventory", "0005_remove_stockquant_reserved_qty_lte_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stockquant",
            name="reserved_qty_lte_quantity",
        ),
        migrations.AddConstraint(
            model_name="stockquant",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="quantity_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockquant",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_qty__gte", 0)),
                name="reserved_qty_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockquant",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", models.F("reserved_qty"))),
                name="reserved_qty_lte_quantity",
            ),
        ),
    ]
