# Generated by Django 5.2.17 on 2026-09-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0007_stockmove_notes_stockmove_reference_stockmove_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockquant",
            options={"ordering": ["location", "product"]},
        ),
    ]
