# Generated by Django 5.2.17 on 2026-09-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_company_options"),
        ("catalog", "0002_product_sku_product_uom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "sku"], name="idx_product_company_sku"
            ),
        ),
    ]
