# Generated by Django 5.2.17 on 2026-09-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_name_product_idx_product_company_sku"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="idx_product_company_sku",
        ),
    ]
