# Generated by Django 5.2.17 on 2026-09-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_company_options"),
        ("catalog", "0004_remove_product_idx_product_company_sku"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("company", "sku"), name="uniq_product_sku_per_company"
            ),
        ),
    ]
