# Generated by Django 5.2.17 on 2026-09-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_uniq_product_sku_per_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
