# Generated by Django 5.2.17 on 2026-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_productcategory_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.UniqueConstraint(
                fields=("name",), name="uniq_product_category_name"
            ),
        ),
    ]
