# Generated by Django 5.2.17 on 2026-09-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_remove_productcategory_uniq_product_category_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productcategory",
            name="uniq_product_category_name",
        ),
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"),
                name="uniq_product_category_name",
                nulls_distinct=False,
            ),
        ),
    ]
