# Generated by Django 5.2.17 on 2026-09-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_company_options"),
        ("catalog", "0010_product_created_at_product_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("sale_price__gte", 0), ("cost_price__gte", 0)),
                name="check_price_constraint",
            ),
        ),
    ]
